logging:
  level:
    '[com.my]': DEBUG
spring:
  datasource:
    url: jdbc:mysql:///jtsys?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
    cache: false
 
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/*/*.xml

server:
  port: 80
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /

page:
  config:
    pageSize: 6